apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo

resources:
  - rbac.yaml
  - workflow-template.yaml

configurations:
  - kustomizeconfig.yaml

images:
  - name: cap-002-terraform-runner
    newName: ghcr.io/yohansenanayake/harvester-testsuite
    digest: sha256:c3c3dde1178ad26db39549a9550df9cd4b466352e2c72bf10069f8713e954744
    
