apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo

resources:
  - rbac.yaml
  - workflow-template.yaml

configurations:
  - kustomizeconfig.yaml

images:
  - name: cap-002-terraform-runner
    newName: ghcr.io/yohansenanayake/harvester-testsuite
    digest: sha256:a300088abeb7f1ad61f256c1887446b3597634ae02e544861606518d4f674e67
    
