apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cap-002-terraform-workspace
  namespace: argo
  labels:
    testsuite.opencloud.wso2.com/capability-id: CAP-002
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: harvester
  resources:
    requests:
      storage: 2Gi
